### PR TITLE
Added * to void *ctx

### PR DESCRIPTION
**Pull request by rtkaratekid**
Added "*" to "void *ctx"

### CODE REVIEW

**Comment by rtkaratekid** [comment]
chapter-4/flamegraphs/bcc_example.py still fails with this trace. I'm just learning so I'm not sure what exactly is going wrong yet. But syntax issues should be fixed.

```
Exactly one of sample_period / sample_freq should be set
Traceback (most recent call last):
  File "bcc_example.py", line 39, in <module>
    fn_name = 'collect_stack_traces')
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 728, in attach_perf_event
    sample_period, sample_freq, pid, i, group_fd)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 715, in _attach_perf_event
    raise Exception("Failed to attach BPF to perf event")
Exception: Failed to attach BPF to perf event
vagrant@ubuntu-bionic:~/linux-observability-with-bpf
```

**Comment by fntlnz** [comment]
@rtkaratekid I'll look into this, thanks for the patch

**Comment by fntlnz** [comment]
Thanks for the contribution @rtkaratekid - there were some more updated PRs fixing the same problems and after getting those merged this one had conflicts and everything reported here seems solved.

Given that, I'll close this one.

However, I appreciated your contribution a lot, and even if it took me a while to review it I'm really happy that you got the time to post here your findings to help others.

Keep up the good work and thanks again.

**Comment by rtkaratekid** [comment]
@fntlnz no worries. I'm working on porting everything to libbpf (because I'm interested) so I may add a pull request for that in the future or just have my own repo people can refer to.

**Pull request closed without merging**
