### PR TITLE
Chapter 3 Makefile and test script

### PR DESCRIPTION
**Pull request by falcondb**
Hi Lerenzo, 
  I am reading the Chapter 3 in your book, and there are a lot of staff in Chapter 3. Just played with the code example in your git repo. I made some development on the code build and test. Feel free to make suggestions and even decline the PR.

**The PR includes:**
- added a script to do rsync between local machine and VM to make development easier.
- made the chapter 3 code working in my environment with a Makefile and a simple test script.

### CODE REVIEW

**Comment by falcondb** [comment]
Hi Lerenzo,
   Feel free to decline this PR. I am a little confusing about my code and my build at this moment. Seems to me the code is using the map helper functions in the _kernel mode_, but I am running it in _user mode_. I am doing more research on the map functions to figure out why it worked.

**Comment by fntlnz** [comment]
Thanks a lot  @falcondb - you are helping a lot I’m very grateful ☺️ - it’s a lot of stuff so it will require some time  to review.
Is this ready for review ?

**Comment by falcondb** [comment]
Yes, it is ready for review. Merry Xmas.

**Comment by falcondb** [comment]
I am closing this PR, since this [blog](https://blogs.oracle.com/linux/notes-on-bpf-4) presents a better build methodology than my PR.

**Comment by fntlnz** [comment]
Ok thanks for looking into this. If you feel like we can improve here please open anew one @falcondb :)

**Pull request closed without merging**
